export const homebankname = [
  { value: "AADHAL HFL", label: "AADHAL HFL" },
  { value: "ADANI CAPITAL", label: "ADANI CAPITAL" },
  { value: "ADITYA BIRLA", label: "ADITYA BIRLA" },
  { value: "AMBIT FIN", label: "AMBIT FIN" },
  { value: "APEC FIN", label: "APEC FIN" },
  { value: "BAJAJ FIN", label: "BAJAJ FIN" },
  { value: "CHOLA MANDALAM", label: "CHOLA MANDALAM" },
  { value: "DCB BANK", label: "DCB BANK" },
  { value: "EQUITAS SFB", label: "EQUITAS SFB" },
  { value: "FIVE STAR FINANCE", label: "FIVE STAR FINANCE" },
  { value: "FULLERTON FINANCE", label: "FULLERTON FINANCE" },
  { value: "HDFC BANK", label: "HDFC BANK" },
  { value: "HINDUJA FINANCE", label: "HINDUJA FINANCE" },
  { value: "HOME FIRST FINANCE", label: "HOME FIRST FINANCE" },
  { value: "ICICI BANK", label: "ICICI BANK" },
  { value: "ICICI HFL", label: "ICICI HFL" },
  { value: "JANA BANK", label: "JANA BANK" },
  { value: "LIC HFL", label: "LIC HFL" },
  { value: "MAHINDRA FINANCE", label: "MAHINDRA FINANCE" },
  { value: "MANIPURAM FINANCE", label: "MANIPURAM FINANCE" },
  { value: "MOTILAL FINANCE", label: "MOTILAL FINANCE" },
  { value: "MUTHOOT FINANCE", label: "MUTHOOT FINANCE" },
  { value: "ORIGO FINANCE", label: "ORIGO FINANCE" },
  { value: "PIRAMAL CAPITAL", label: "PIRAMAL CAPITAL" },
  { value: "PREPCO HOME FINANCE", label: "PREPCO HOME FINANCE" },
  { value: "SBFC FINANCE", label: "SBFC FINANCE" },
  { value: "SUNDARAM FINANCE", label: "SUNDARAM FINANCE" },
  { value: "VERITOS FINANCE", label: "VERITOS FINANCE" },
  { value: "VISTARA HFL", label: "VISTARA HFL" },
];
